[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]
fs_permissions = [{ access = "read-write", path = "../ai_agent/config.json" }]

[profile.ci]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
